# .NET 8 çalışma zamanı ortamını kullan
FROM mcr.microsoft.com/dotnet/aspnet:8.0

# Uygulama çalışma dizini
WORKDIR /app

# Mevcut klasördeki her şeyi konteynere kopyala
COPY . .

# Uygulamayı başlat (dll adı küçük harfli: tarifkapida.dll)
ENTRYPOINT ["dotnet", "tarifkapida.dll"]
